PRODUCT_PACKAGES += \
    PixelAccessibilityMenu \
    PixelBuiltInPrintService \
    CellBroadcastReceiverOverlay \
    CellBroadcastServiceOverlay \
    PixelContactsProvider \
    GoogleConfigOverlay \
    GoogleDeviceLockControllerOverlay \
    GoogleWebViewOverlay \
    ManagedProvisioningPixelOverlay \
    PixelConfigOverlay2018 \
    PixelConfigOverlay2019 \
    PixelConfigOverlay2019Midyear \
    PixelConfigOverlay2021 \
    PixelConfigOverlayCommon \
    PixelConnectivityOverlay2023 \
    PixelTetheringOverlay2021 \
    SettingsGoogleOverlay2021AndNewer \
    PixelSettingsGoogle \
    PixelSettingsProvider \
    PixelStorageManagerGoogle \
    SystemUIGXOverlay \
    PixelSystemUIGoogle \
    PixelTeleService \
    PixelTelecom \
    PixelTelephonyProvider \
    Pixelframework-res \
